// This file is generated by the Supabase CLI
// You can regenerate it using: supabase gen types typescript --local

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    // Add your database types here as needed
    // This can be auto-generated using the Supabase CLI
}
